# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\logs.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Logfile(object):
    def setupUi(self, Logfile):
        Logfile.setObjectName("Logfile")
        Logfile.resize(645, 500)
        Logfile.setMinimumSize(QtCore.QSize(0, 0))
        self.gridLayout = QtWidgets.QGridLayout(Logfile)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(Logfile)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)

        self.retranslateUi(Logfile)
        QtCore.QMetaObject.connectSlotsByName(Logfile)

    def retranslateUi(self, Logfile):
        _translate = QtCore.QCoreApplication.translate
        Logfile.setWindowTitle(_translate("Logfile", "Dialog"))
